/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Guilherme
 */
public class ConfirmarPedido extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmarPedido
     */
    public ConfirmarPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConfirmarPedido = new javax.swing.JPanel();
        lbCabecalho = new javax.swing.JLabel();
        spPedido = new javax.swing.JScrollPane();
        listaPedido = new javax.swing.JList<>();
        pnlConfirmarPedido2 = new javax.swing.JPanel();
        bCancelar = new javax.swing.JButton();
        bEditar = new javax.swing.JButton();
        bPagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Miqueias Fast Food - Finalizar Pedido");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo_cachorro_quente.png")).getImage());

        pnlConfirmarPedido.setBackground(new java.awt.Color(244, 244, 244));

        lbCabecalho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cabecalho.png"))); // NOI18N

        listaPedido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seu Pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Emoji", 3, 12))); // NOI18N
        listaPedido.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "..." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        spPedido.setViewportView(listaPedido);

        pnlConfirmarPedido2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bCancelar.setText("Cancelar");

        bEditar.setText("Editar");
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });

        bPagar.setText("Pagar");
        bPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConfirmarPedido2Layout = new javax.swing.GroupLayout(pnlConfirmarPedido2);
        pnlConfirmarPedido2.setLayout(pnlConfirmarPedido2Layout);
        pnlConfirmarPedido2Layout.setHorizontalGroup(
            pnlConfirmarPedido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfirmarPedido2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(bCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bPagar)
                .addGap(60, 60, 60)
                .addComponent(bEditar)
                .addGap(107, 107, 107))
        );
        pnlConfirmarPedido2Layout.setVerticalGroup(
            pnlConfirmarPedido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfirmarPedido2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlConfirmarPedido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar)
                    .addComponent(bEditar)
                    .addComponent(bPagar))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlConfirmarPedidoLayout = new javax.swing.GroupLayout(pnlConfirmarPedido);
        pnlConfirmarPedido.setLayout(pnlConfirmarPedidoLayout);
        pnlConfirmarPedidoLayout.setHorizontalGroup(
            pnlConfirmarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfirmarPedidoLayout.createSequentialGroup()
                .addComponent(lbCabecalho)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConfirmarPedidoLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(pnlConfirmarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlConfirmarPedido2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spPedido))
                .addGap(114, 114, 114))
        );
        pnlConfirmarPedidoLayout.setVerticalGroup(
            pnlConfirmarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfirmarPedidoLayout.createSequentialGroup()
                .addComponent(lbCabecalho)
                .addGap(56, 56, 56)
                .addComponent(spPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlConfirmarPedido2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(101, 101, 101))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlConfirmarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlConfirmarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPagarActionPerformed
        // TODO add your handling code here:
        new Pagamento().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bPagarActionPerformed

    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmarPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bEditar;
    private javax.swing.JButton bPagar;
    private javax.swing.JLabel lbCabecalho;
    private javax.swing.JList<String> listaPedido;
    private javax.swing.JPanel pnlConfirmarPedido;
    private javax.swing.JPanel pnlConfirmarPedido2;
    private javax.swing.JScrollPane spPedido;
    // End of variables declaration//GEN-END:variables
}
